config/routes.rb
Rails.application.routes.draw do
  get "welcome/login" => "welcome#login", as: :login

  get "welcome/fetch_repo" => "welcome#fetch_repo"

  resources :users do
    get 'edit_user/:option' => "users#edit_user", as: :js_edit
    post 'edit_user/:option' => "users#update_user", as: :js_update
  end

  resources :portfolio
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'new_guest', to: 'users#create', as: 'new_guest'

  root "welcome#index"

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :repos
  serialize :languages, Array
  has_many :repos, dependent: :destroy
  has_one :basic_profile, dependent: :destroy
  has_many :positions, dependent: :destroy
  has_many :linkedin_oauths, dependent: :destroy

  # validates_presence_of :email, :password_digest, unless: :guest?
  # validates_uniqueness_of :username, allow_blank: true
  # validates_confirmation_of :password


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.profile_url = auth.info.image
      user.first_name = auth.info.name
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.save!
    end
  end


  def fetch_repo(github_username)
    @repos = []
    github = Github.new
    lang = []
    @response = github.repos.list user: github_username
    @response.each do |repo|
      @repos << Repo.new(name: repo.name, description: repo.description, url: repo.html_url, forks_url: repo.forks_url, user: self, language: repo.language)
      lang << repo.language if repo.language
    end
    self.languages = lang.uniq
    self.save
    Repo.import @repos
  end

  def create_linkedin_profile(credentials)
    access= self.linkedin_oauths.first_or_create(token: credentials.token, secret: credentials.secret)
    @client = LinkedIn::Client.new
    @client.authorize_from_access(access.token, access.secret)
    profile = @client.profile( fields:
        ["first-name", "last-name", "maiden-name",
        "formatted-name" ,:headline, :location, :industry, :summary,
        :specialties, :positions, "picture-url", "public-profile-url"]
    )
    create_basic_profile(profile)
  end

  def create_basic_profile(profile)
    basic_profile = profile.to_hash.reject{|key| key.to_s =~ /positions/}
    basic_profile[:user] = self
    basic_profile[:location] = basic_profile["location"]["name"]
    basic_profile = BasicProfile.create(basic_profile)
    create_positions(profile.positions.all)
  end

  def create_positions(positions)
    all_positions = []
    positions.each{ |p|
        user_position = {
          title: p.title,
          summary: p.summary,
          start_date: Date.parse("1/#{p.start_date.month ? p.start_date.month : 1}/#{p.start_date.year}"),
          is_current: p.is_current,
          company: p.company.name
        }
        user_position[:end_date] = Date.parse("1/#{p.end_date.month ? p.end_date.month : 1}/#{p.end_date.year}") unless p.is_current
        all_positions << self.positions.new(user_position)
      }
      Position.import(all_positions)
  end
   def fullname
     ("#{first_name}" ' ' "#{last_name}".capitalize if first_name && last_name.present?) || ("Guest".capitalize if guest) || nil
   end

    def self.new_guest
      new { |u| u.guest = true }
    end

    def name
      guest ? "Guest" : first_name
    end

    def assign_other_guest_records_to(user)
      repos.update_all(user_id: user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :current_user, :except => [:new]

  def index
    if current_user
      redirect_to user_path(@current_user.id)
    else
      redirect_to root_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = params[:user] ? User.new(params[:user]) : User.new_guest
    if @user.save
      current_user.assign_other_guest_records_to(@user) if current_user && current_user.guest?
      login_user(@user)
      redirect_to user_path(@user)
    else
      flash[:error] = "Could not create account. Please try again."
      redirect_to root_url
    end
  end

  def show
    @user = current_user || User.find_by_id(params[:id])
    if @user
      @basic_profile = @user.basic_profile
      @positions = @user.positions.decorate
      @repos = @user.repos
    end
    redirect_to root_url if !@user
  end

  def edit_user
    @option = params[:option]
    respond_to do |format|
      format.js { render "show_edit_box.js" }
    end if @option
  end

  def update_user
    @option = (user_params && user_params[:option]) ? user_params[:option] : nil
    update_user_info if @option
    respond_to do |format|
      format.js { render "update_user.js" }
    end
  end


  private


  def user_params
    params.require(:user).permit(:avatar, :username, :gender, :first_name, :middle_name, :last_name, :dob, :nationality, :address, :phone_number, :bio, :username, :email, :password, :password_confirmation, :option, :fullname) if params.has_key? "user"
  end

  def update_user_info
    if @option == "fullname"
      user_fullname
    else
      @current_user[@option] = user_params[@option]
    end
    @current_user.save
  end

  def user_fullname
    fullname = user_params[@option].split(" ")
    @current_user.first_name = fullname[0]
    @current_user.last_name = fullname[1]
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def sign_in_provider
    {
        linkedin: {name: "Linkedin", class: "#007BB6", icon_class: "fa-linkedin"},
        github: {name: "Github", class: "#444444", icon_class: "fa-github"}
    }
  end

  def unlinked_account
    has_linked_github = current_user.repos.any?
    has_linked_linkedin = current_user.basic_profile.present?
    unless has_linked_linkedin && has_linked_github
      if has_linked_linkedin
        link_github
      elsif has_linked_github
        link_linkedin
      end
    end
  end

  def link_github
    content_tag :li do
      link_to 'Connect to Github', '/auth/github'
    end
  end

  def link_linkedin
    content_tag :li do
      link_to 'Connect to LinkedIn', '/auth/linkedin'#, class: "btn btn-linkedin"
    end
  end
end

app/views/users/_add_fullname.html.erb
<% if @current_user %>
  <% option ||= @option.nil? ? "fullname" : @option %>
    <div class="edits user_<%= option %>">
      <%=link_to @current_user.fullname, user_js_edit_path(@current_user.id, "#{option}"), class: "edit_link", remote: :true %>
    </div>
<% else %>
  <%= @user.fullname %>
<% end %>

app/views/users/_contact.html.erb
<div class="ewf-inline-style">
    <style media="all" type="text/css">
        .vc_custom_1416387239821 {
            margin-bottom: 0px !important;
            padding-top: 110px !important;
            padding-bottom: 110px !important;
            background-image: url(http://bitpublimedia.ro/themeforest/versus-resume-wp/wp-content/uploads/2014/11/1920x2000.jpg?id=77) !important;
        }
    </style>
</div>

<div class="ewf-full-width-section nospacing">
    <div id="contact" class="ewf-row vc_custom_1416387239821 parallax row-overlay parallax-enabled">
        <div class="row-overlay ewf-row-overlay-pattern"></div>
        <div class="row-overlay-inner">
            <div class="ewf-span12 vc_column_container">
                <div class="ewf-wrapper">
                    <div class="ewf-row">
                        <div class="ewf-span12 vc_column_container">
                            <div class="ewf-wrapper">
                                <div class="text-center">
                                    <div class="headline ">
                                        <h1>Contact</h1>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="ewf-row">
                        <div class="ewf-span4 vc_column_container">
                            <div class="ewf-wrapper">

                                <div class="wpb_widgetised_column wpb_content_element">
                                    <div class="ewf-wrapper">
                                        <div id="text-4" class="widget widget_text">
                                            <h3 class="widget-title"><span>Get in touch</span></h3>
                                            <div class="textwidget">Nullam et ante sit amet tortor sollicitudin congue. Maecenas ut pharetra sapien. Suspendisse nec suscipit risus. Cras vel lorem nec sem condimentum pharetra sed at enim.</div>
                                        </div>
                                        <div id="ewf_widget_contact_info-2" class="widget ewf_widget_contact_info">
                                            <h3 class="widget-title"><span>My Address</span></h3>
                                            <ul>
                                                <li><i class="ifc-home"></i>777 Fifth Avenue / New York / NY 10153</li>
                                                <li><i class="ifc-phone1"></i>(123) 456-7890</li>
                                                <li><i class="ifc-message"></i>office@yoursite.com</li>
                                            </ul>
                                        </div>
                                        <div id="ewf_widget_social_media-2" class="widget ewf_widget_social_media">
                                            <h3 class="widget-title"><span>I’m also on social networks</span></h3>
                                            <div class="fixed"><a class="facebook-icon social-icon" href="#"><i class="fa fa-facebook"></i></a><a class="twitter-icon social-icon" href="#"><i class="fa fa-twitter"></i></a>
                                                <a class="googleplus-icon social-icon" href="#"><i class="fa fa-google-plus"></i>
                                                </a><a class="linkedin-icon social-icon" href="#"><i class="fa fa-linkedin"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="ewf-span8 vc_column_container">
                            <div class="ewf-wrapper">
                                <div role="form" class="wpcf7" id="wpcf7-f4-p5-o1" lang="en-US" dir="ltr">
                                    <div class="screen-reader-response"></div>
                                    <form action="/themeforest/versus-resume-wp/#wpcf7-f4-p5-o1" method="post" class="wpcf7-form" novalidate="novalidate">
                                        <div style="display: none;">
                                            <input type="hidden" name="_wpcf7" value="4">
                                            <input type="hidden" name="_wpcf7_version" value="4.3">
                                            <input type="hidden" name="_wpcf7_locale" value="en_US">
                                            <input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f4-p5-o1">
                                            <input type="hidden" name="_wpnonce" value="fd33b32ea0">
                                        </div>
                                        <p><span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="name"></span>
                                        </p>
                                        <p><span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" aria-invalid="false" placeholder="e-mail address"></span>
                                        </p>
                                        <p><span class="wpcf7-form-control-wrap your-subject"><input type="text" name="your-subject" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="subject"></span>
                                        </p>
                                        <p><span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea wpcf7-validates-as-required" aria-required="true" aria-invalid="false" placeholder="message"></textarea></span>
                                        </p>
                                        <p>
                                            <input type="submit" value="Send" class="wpcf7-form-control wpcf7-submit">
                                            <img class="ajax-loader" src="http://bitpublimedia.ro/themeforest/versus-resume-wp/wp-content/plugins/contact-form-7/images/ajax-loader.gif" alt="Sending ..." style="visibility: hidden;">
                                        </p>
                                        <div class="wpcf7-response-output wpcf7-display-none"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/_current_user_prop.html.erb
<% option ||= @option.nil? ? "" : @option %>
<h3 class="user_<%= option %>"><%= @current_user[option] %>
<%=link_to "Edit", user_js_edit_path(@current_user, "#{option}"), class: "edit_link", remote: :true %></h3>

app/views/users/_js_textbox.html.erb
<%
  request_path ||= ""
  field_to_edit ||= "Something's wrong. Please retry."
  default_text = @current_user.fullname if field_to_edit == "fullname"
  placeholder ||= "Edit #{field_to_edit}"
%>

<% size = field_to_edit == "fullname" ? {rows: 1} : {} %>
  <%=form_for request_path, remote: true do |f| %>
    <div class="js-textbox">
       <div class="form-group">
         <%= f.text_area(field_to_edit, {class: "form-control", id: "js-edit-text", placeholder: placeholder, value: default_text }.merge(size) ) %>
         <%= f.hidden_field :option, value: field_to_edit %>
       </div>
       <div>
         <%= button_tag(type: 'submit',  class: "btn btn-sm btn-success right", id: 'submit-js-edit') do %>
              <i class="fa fa-save"></i>&nbsp;&nbsp;Save
            <% end %>
      </div>
    </div>
  <% end %>

app/views/users/_navbar.html.erb
        <div class="sticky-wrapper">
            <div id="nav" class="">

                <div class="ewf-row">
                    <div class="ewf-span3">

                        <!-- // Logo // -->
                        <a hrer="#" id="logo" class="fullname">
                            <%= @user.fullname || "No name yet" %>
                        </a>

                    </div>
                    <!-- end .ewf-span3 -->
                    <div class="ewf-span9 no-space">

                        <a href="#" id="mobile-menu-trigger" class="mobile-menu-closed">
                            <i class="fa fa-bars"></i>
                        </a>

                        <!-- // Menu // -->
                        <ul id="menu" class="sf-menu fixed sf-js-enabled">
                              <%#= link_github %>
                              <%= unlinked_account if current_user == @user %>
                            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20 active">
                                <a title="Personal Details" href="#personal-details" rel="page-20">
                                    <span>Personal Details</span>
                                </a>
                            </li>
                            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-21">
                                <a title="Experience" href="#experience" rel="page-21">
                                    <span>Experience</span>
                                </a>
                            </li>
                            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-22">
                                <a title="Education" href="#education" rel="page-22">
                                    <span>Education</span>
                                </a>
                            </li>


                            <!-- <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-23">
                                <a title="References" href="#references" rel="page-23">
                                    <span>References</span>
                                </a>
                            </li> -->
                            <!-- <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-24">
                                <a title="Skills" href="#skills" rel="page-24">
                                    <span>Skills</span>
                                </a>
                            </li> -->
                            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-25">
                                <a title="Portfolio" href="#portfolio" rel="page-25">
                                    <span>Portfolio</span>
                                </a>
                            </li>
                            <li class="menu-item menu-item-type-custom menu-item-object-custom menu-item-26">
                                <a title="Contact" href="#contact" rel="page-26">
                                    <span>Contact</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- end .ewf-span9 -->
                </div>
                <!-- end .ewf-row -->

            </div>
        </div>
        <!-- end #nav -->

app/views/users/_personal_details.html.erb
        <div class="ewf-full-width-section nospacing">
            <div id="personal-details" class="ewf-row user-details">
                <div class="ewf-span12 vc_column_container">
                    <div class="ewf-wrapper">
                        <div class="ewf-inline-style">

                            <style media="all" type="text/css">
                                .vc_custom_1416491652026 {
                                    margin-bottom: 0px !important;
                                }
                            </style>

                        </div>
                        <div class="ewf-row vc_custom_1416491652026">
                            <div class="ewf-span12 vc_column_container">
                                <div class="ewf-wrapper">
                                    <div class="text-center">
                                        <div class="headline ">
                                            <p><span style="background-color:#fff;">Who am I?</span>
                                            </p>
                                            <h1>Personal Details</h1>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="ewf-row">
                            <div class="ewf-span3 vc_column_container">
                                <div class="ewf-wrapper">

                                    <div class="wpb_single_image wpb_content_element vc_align_left">
                                        <div class="ewf-wrapper">

                                            <img width="270" height="270" src= <%= "#{@user.profile_url || ""}" %> class=" vc_box_border_grey attachment-full" alt="270x270" />
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="ewf-span4 vc_column_container">
                                <div class="ewf-wrapper">
                                    <ul class="personal-details ">
                                        <li>Name: <%= @user.first_name %></li>
                                        <!-- <li>Date of birth: 14 February 1986</li> -->
                                        <%= content_tag :li do %>
                                          Location: <%= @basic_profile.location %>
                                        <% end if @basic_profile %>
                                        <!-- <li>Address: <%= %></li> -->
                                        <!-- <li>Phone: (123) - 456-7890</li> -->
                                        <li>Email: <%= @user.email %></li>
                                      <!-- <li>Name:
                                        <span><%= render partial: "users/user_info", locals: {option: "fullname"} %><span>
                                      </li>
                                        <li>
                                          Date of birth: <%= render partial: "users/user_info", locals: {option: "fullname"} %>
                                        </li>
                                        <li>Nationality: Citizen of Envato</li>
                                        <li>Address: 23 High Hope Blvd. Some City</li>
                                        <li>Phone: (123) - 456-7890</li>
                                        <li>Email: john.smith@jbs.com</li> -->
                                    </ul>
                                </div>
                            </div>

                            <div class="ewf-span5 vc_column_container">
                                <div class="ewf-wrapper">

                                    <div class="wpb_text_column wpb_content_element ">
                                        <div class="ewf-wrapper">
                                            <h3 class="text-uppercase">Profesional Profile</h3>
                                            <!-- <p>
                                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare sem sed quam tempus aliquet vitae eget dolor. Proin eu ultrices libero. Curabitur vulputate vestibulum elementum. Suspendisse id neque a nibh mollis blandit. Quisque varius eros ac
                                                purus dignissim.
                                            </p>
                                            <p>
                                                Praesent sit amet massa suscipit, auctor sapien non, egestas felis. Maecenas mattis aliquet est vitae dignissim. Suspendisse aliquam lacus mauris, id placerat felis faucibus quis. Suspendisse potenti. Etiam mattis, eros id porta iaculis.
                                            </p> -->
                                            <%= simple_format(@basic_profile.summary) if @basic_profile %>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

app/views/users/_skills.html.erb
<div class="ewf-row">

    <div class="ewf-span8 vc_column_container">
        <div class="ewf-wrapper">

            <div class="wpb_text_column wpb_content_element  vc_custom_1416489486710">
                <div class="ewf-wrapper">
                    <h2 class="text-uppercase">Software</h2>

                </div>
            </div>
            <div class="fixed ">
                <div class="progress-bar-description">Photoshop <span style="left:86%;">86%</span>
                </div>
                <div class="progress-bar" style="background-color:#5f5f5f"><span class="progress-bar-outer" data-width="86"><span class="progress-bar-inner" style="background-color:#252525"></span></span>
                </div>
                <!-- end .progress-bar -->
            </div>
            <div class="fixed ">
                <div class="progress-bar-description">Corel Draw <span style="left:73%;">73%</span>
                </div>
                <div class="progress-bar" style="background-color:#5f5f5f"><span class="progress-bar-outer" data-width="73"><span class="progress-bar-inner" style="background-color:#252525"></span></span>
                </div>
                <!-- end .progress-bar -->
            </div>
            <div class="fixed ">
                <div class="progress-bar-description">Adobe Illustrator <span style="left:79%;">79%</span>
                </div>
                <div class="progress-bar" style="background-color:#5f5f5f"><span class="progress-bar-outer" data-width="79"><span class="progress-bar-inner" style="background-color:#252525"></span></span>
                </div>
                <!-- end .progress-bar -->
            </div>
            <div class="fixed ">
                <div class="progress-bar-description">Adobe InDesign <span style="left:57%;">57%</span>
                </div>
                <div class="progress-bar" style="background-color:#5f5f5f"><span class="progress-bar-outer" data-width="57"><span class="progress-bar-inner" style="background-color:#252525"></span></span>
                </div>
                <!-- end .progress-bar -->
            </div>
            <div class="fixed ">
                <div class="progress-bar-description">Cinema 4D <span style="left:44%;">44%</span>
                </div>
                <div class="progress-bar" style="background-color:#5f5f5f"><span class="progress-bar-outer" data-width="44"><span class="progress-bar-inner" style="background-color:#252525"></span></span>
                </div>
                <!-- end .progress-bar -->
            </div>
        </div>
    </div>

    <div class="ewf-span4 vc_column_container">
        <div class="ewf-wrapper">

            <div class="wpb_text_column wpb_content_element  vc_custom_1416489580244">
                <div class="ewf-wrapper">
                    <h2 class="text-uppercase">Recognitions</h2>

                </div>
            </div>
            <div class="icon-box-1 ">
                <i class="ifc-drafting_compass"></i>
                <div class="icon-box-content">
                    <h3>International Design Awards 2014</h3>
                    <p>15 March 2014 / New York State University
                        <br>Place: 3</p>

                </div>
                <!-- end .icon-box-content -->
            </div>
            <!-- end .icon-box-1 -->
            <div class="icon-box-1 ">
                <i class="ifc-king"></i>
                <div class="icon-box-content">
                    <h3>Logo Design Contest Chicago 2013</h3>
                    <p>12 October 2013 / Chicago House of Art
                        <br>Place: 2</p>

                </div>
                <!-- end .icon-box-content -->
            </div>
            <!-- end .icon-box-1 -->
            <div class="icon-box-1 ">
                <i class="ifc-pain_brush"></i>
                <div class="icon-box-content">
                    <h3>Web Design Contest New York 2013</h3>
                    <p>12 October 2013 / New York Technology Office
                        <br>Place: 2</p>

                </div>
                <!-- end .icon-box-content -->
            </div>
            <!-- end .icon-box-1 -->
        </div>
    </div>
</div>

app/views/users/_user_info.html.erb
<% option ||= "" %>
<div id="user_<%= option %>" class="user-edits">
  <% if option != "fullname" %>
  <% if @user[option] %>
   <%= render partial: "current_user_prop", locals: {option: option} %>
  <% else %>
   <%= render("users/add_#{option}") %>
  <% end %>
</div>

app/views/users/_work_experience.html.erb
                                    <div class="ewf-row cv-section ">
                                        <div class="ewf-span3">

                                            <div class="cv-section-title">

                                                <h1>
                                      						<span>
                                      							<%= position.start_date.year %>
                                      							<small><%= position.start_date.strftime("%B") %></small>
                                      						</span>
                                      						-
                                      						<span>
                                      							<%= position.current_position_or_ended%>
                                      							<small></small>
                                      						</span>
                                      					</h1>

                                                <h3><%= position.company %></h3>

                                            </div>
                                            <!-- end .cv-section-title -->

                                        </div>
                                        <!-- end .ewf-span3 -->

                                        <div class="ewf-span9">
                                            <div class="cv-item">
                                                <h3><%= position.title %></h3>
                                                <%= simple_format(position.summary) %>
                                            </div>
                                            <!-- end .cv-item -->

                                        </div>
                                        <!-- end .ewf-span9 -->
                                    </div>
                                    <!-- end .cv-section -->

app/views/users/show_edit_box.js.erb
$(".parallax.full-screen a").hide();
$("#user_<%= @option %>").html('<%=j render(partial: "users/js_textbox", locals: {request_path: "user", field_to_edit: "#{@option}", default_text: "#{@current_user[@option]}"}) %>');