config/routes.rb
Rails.application.routes.draw do
  get "welcome/login" => "welcome#login", as: :login

  get "welcome/fetch_repo" => "welcome#fetch_repo"

  resources :users do
    get 'edit_user/:option' => "users#edit_user", as: :js_edit
    post 'edit_user/:option' => "users#update_user", as: :js_update
  end

  resources :portfolio
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'new_guest', to: 'users#create', as: 'new_guest'

  root "welcome#index"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def login
  end

  def signup
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_login_form.html.erb
<!-- Trigger the modal with a button -->

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Login Form</h4>
      </div>
      <div class="modal-body">
        <% sign_in_provider.each do |provider, helper| %>
          <div class="col-md-5 sso_option">
            <%= link_to signin_path(provider.to_s), class: "btn btn-lg btn-block btn-social btn-linkedin", style: "color: #fff !important;background-color: #{helper[:class]};" do %>
              <%= "#{content_tag :i, nil, class: "fa #{helper[:icon_class]} ", style:"color: #fff !important;"} #{helper[:name]}".html_safe %>
            <% end %>
          </div>
        <% end %>
        <p>Email</p>
        <p>Password</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/welcome/index.html.erb
<!-- Navigation -->
<div class="body homepage">
   <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
       <div class="container">
           <div class="navbar-header">
               <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                   <i class="fa fa-bars"></i>
               </button>
               <a class="navbar-brand page-scroll home home-title" href="#page-top">
                   <i class="fa fa-play-circle"></i> Profiler
               </a>
           </div>

           <!-- Collect the nav links, forms, and other content for toggling -->
           <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
               <ul class="nav navbar-nav">
                   <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                   <li class="hidden">
                       <a href="#page-top"></a>
                   </li>
                   <% if current_user %>
                       <li>
                          <%= link_to "Logged in as #{current_user.name}", user_path(current_user.id) %>
                       </li>
                    <% end %>

                    <% if current_user && !current_user.guest? %>
                      <li>
                          <%= link_to "My Profile", user_path(current_user.id), class: "page-scroll" %>
                      </li>
                      <li><%= link_to "Log Out", signout_path %></li>
                    <% else %>
                      <li><%= link_to "Try as Guest", new_guest_path %></li>

                      <li>
                          <%= link_to "Login / Signup", login_path, {:remote => true, class: "page-scroll", "data-target" => "#myModal", "data-toggle" => "modal" } %>
                      </li>

                      <li>
                          <%= link_to "View Sample profiles", "#", class: "page-scroll" %>
                      </li>
                    <% end %>
               </ul>
           </div>
           <!-- /.navbar-collapse -->
       </div>
       <!-- /.container -->
   </nav>

   <!-- Intro Header -->
   <header class="intro">
       <div class="intro-body">
           <div class="container">
               <div class="row">
                   <div class="col-md-8 col-md-offset-2">
                       <h1 class="brand-heading">Profiler</h1>
                       <p class="intro-text">A free and easy to use Profile Generator for Software Developers<br>Created by Team Sockets</p>
                       <a href="#about" class="btn btn-circle page-scroll">
                           <i class="fa fa-angle-double-down animated"></i>
                       </a>
                   </div>
               </div>
           </div>
       </div>
   </header>

   <!-- About Section -->
   <section id="about" class="container content-section text-center">
       <div class="row">
           <div class="col-lg-8 col-lg-offset-2">
               <h2>About Profiler</h2>
               <p>Profiler is a free online Profile Generator for Software Developers. It provides a platform for Software Developers to easily create a detailed, professional about me page to showcase their Skillsets anad Projects.</p>
               <p>It's easy to use and setup using your Github or Linkedin Account. You can also <%= link_to "view a sample", "#" %> online profile here.</p>
           </div>
       </div>
   </section>


   <!-- Contact Section -->
   <section id="contact" class="container content-section text-center">
       <div class="row">
           <div class="col-lg-8 col-lg-offset-2">
               <h2>Contact Team Socket</h2>
               <p>Feel free to email us to provide some feedback on our site, give us suggestions and your experience using Profiler or just to have a friendly chat.</p>
               <p><a href="mailto:feedback@startbootstrap.com">feedback@teamsocket.com</a>
               </p>
               <ul class="list-inline banner-social-buttons">
                   <li>
                       <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                   </li>
                   <li>
                       <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                   </li>
                   <li>
                       <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
                   </li>
               </ul>
           </div>
       </div>
   </section>


   <!-- Footer -->
   <footer>
       <div class="container text-center">
           <p>Copyright &copy; Team Socket 2015</p>
       </div>
   </footer>

  <%= render "login_form" %>
</div>

app/views/welcome/login.js.erb
$("#dialog").modal("show");

app/views/welcome/repo.html.erb
<div class="row" style="background-color: grey !important;">
  <div  style="margin: 30px 10px;">
    <% @response.each do |repo| %>
      <% #repo.each do |key, value|%>
       <div class="col-md-5 ">
          <pre><%= repo.name %></pre>
          <label><%= repo.description %></label>
        </div>
      <%# end %>
    <% end %>
  </div>
</div>